### PR TITLE
Vkontakte added, facebook locale added, fix g+ button.

### PR DESCRIPTION
**Pull request by artemasmith**
May I insert my name in authors field?

### CODE REVIEW

**Comment by kristianmandrup** [comment]
Sure ;) Good job!

**Comment by kristianmandrup** [comment]
@iffyuva can you please run the tests and check, then merge ;) thanks!

**Comment by artemasmith** [comment]
I've tested the code in my enviroment, all was good.

**Comment by iffyuva** [comment]
hi @artemasmith i shall check this PR and merge it. meanwhile, can you rebase master into this PR, or rebase onto latest master, since this PR is not cleanly mergeable? thanks.

**Comment by artemasmith** [comment]
Hi, iffyuva, i thought I checkouted from latest  stable branch. I'm not overcvalified in git, how can I rebase my code from a different repository branch?

**Comment by artemasmith** [comment]
Ou, I see. I'm a contributor now.

**Comment by kristianmandrup** [comment]
@artemasmith I guess you have taken over this project now ;)
The latest Rubygems version is quite dated... https://rubygems.org/gems/social-buttons
Would be nice if you could push a new version to rubygems with all the latests improvements, now that you are a contributor :)

**Pull request closed without merging**
